# Generated by Django 4.0.2 on 2022-02-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assessMessage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('messageInfo', models.CharField(max_length=500, verbose_name='短信内容')),
                ('percentage', models.FloatField(verbose_name='是诈骗信息的概率')),
            ],
        ),
        migrations.CreateModel(
            name='redis',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mkey', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('expireTime', models.DateTimeField(verbose_name='过期时间')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('1', '近期新闻'), ('2', '经典案例')], default='1', max_length=1, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='news',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
