# Generated by Django 4.0.2 on 2022-02-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_assessmessage_id_alter_news_id_alter_redis_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
